services:
  app:
    depends_on:
      - redis
      - postgres
    build: .
    ports:
      - 10101:8080

  redis:
    image: 'redis:latest'
    container_name: consultant-redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:15-alpine
    container_name: consultant-postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: consultant
    ports:
      - 5432:5432